# Compiliert und linkt alle .cpp-Dateien im aktuellen Verzeichnis als Projekt,
# d.h. es gibt danach EIN ausführbares Programm, so dass es nur exakt EIN 
# main-Programm im Verzeichnis geben darf
# GNU C++ wird als Compiler angenommen

include ../../make/makeProject
